---
name: "Jellyfin.Plugin.ExcludedLibraries"
guid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version: "1.1.0.0"
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "shaheer"
overview: "Create home sections with valid media files only"
description: >
  This plugin integrates with the Home Screen Sections plugin to create custom
  sections that display content with valid, accessible files. Automatically
  filters out broken symlinks, missing files, and items with corrupt metadata.
  Perfect for ensuring your home screen only shows playable content.
category: "General"
artifacts:
  - "Jellyfin.Plugin.ExcludedLibraries.dll"
  changelog: >
    ## 1.0.0
    
    Initial release
    
    - Custom home sections for Jellyfin
    - Filter media by valid file sizes (excludes broken/missing files)
    - Content type selection (Movies, TV Series, Music Albums)
    - Multiple sorting options (Date Added, Date Played, Release Date, Name, Random)
    - Auto-registration with Home Screen Sections plugin
    - Smart grouping of episodes to series and tracks to albums
    - Efficient single-query filtering approach
    - Comprehensive logging with [ExcludedLibraries] prefix
    - Web UI configuration page

